name: "Automatically label pull requests"

on:
- pull_request_target

jobs:
  labelr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"